### ISSUE TITLE
Allow change bottom menu MATERIAL

### ISSUE THREAD

**Issue by nhanledev** [Oribuin/EternalTags#4]
Please allow in the config to change the Material of the bottom in the menu, current default is some glass panel and I could not find anywhere to change these glasses.

It is called fillerItem in your code.

Thank you <3

![image](https://user-images.githubusercontent.com/28459250/145681620-8686cf05-093f-471c-8df4-ad3434746b0d.png)

**Comment by Oribuin** [comment]
Sorry for the incredibly late response again, This was changed in v1.1.0 Recode (#6). You can find the pre release in my discord server.
```yaml
# The border item at the bottom of the gui.
border-item:
  enabled: true
  material: GRAY_STAINED_GLASS_PANE
```
